"""Assemble the delivery bundle.

    delivery/<task-name>/
    ├── task/                       the reusable Harbor task package
    ├── jobs/
    │   ├── oracle/                 reward 1.0 — proves solvable
    │   ├── nop/                    reward 0.0 — proves non-trivial
    │   └── <model>/attempt-{1..k}/ trajectory.json (ATIF) + verifier/
    ├── pairs.jsonl                 failed ATIF <-> gold ATIF, per attempt
    ├── failure_analysis.json       labelled modes with evidence spans
    └── manifest.json               p̂, CI, n, level, tier, seed, knobs, model snapshot

The split matters: `task/` is the reusable asset, `jobs/` is the evidence, and
`pairs.jsonl` is what actually trains. A client receiving only the last of
those cannot reproduce or audit anything.

Canary note: files under task/ carry Harbor's canary and are eval-only.
pairs.jsonl and the trajectories do not — they are the training product. The
manifest records which is which so the boundary survives handoff.
"""

from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

MANIFEST_SCHEMA = "mcp-stump/manifest-v1"


def _load(p: Path, default: Any = None) -> Any:
    if not p.is_file():
        return default
    try:
        return json.loads(p.read_text())
    except (json.JSONDecodeError, OSError):
        return default


def build_manifest(summary: dict, task_dir: Path, trials: Path) -> dict:
    """Everything needed to reproduce or audit the measurement."""
    import tomllib

    cfg = tomllib.loads((task_dir / "task.toml").read_text())
    md = cfg.get("metadata", {})
    env = cfg.get("environment", {})
    metrics = summary.get("metrics", {})

    gt = trials / "ground_truth"
    spec = _load(gt / "judge_spec.json", {})
    plan = _load(gt / "gold_plan.json", [])

    return {
        "schema": MANIFEST_SCHEMA,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "task": {
            "name": cfg.get("task", {}).get("name", task_dir.name),
            "version": cfg.get("task", {}).get("version"),
            # Authored capability level (ETOM axis) and MEASURED difficulty are
            # orthogonal -- conflating them is the classic error.
            "capability_level": md.get("capability_level"),
            "difficulty_tier": md.get("difficulty_tier"),
            "stump_levers": md.get("stump_levers", []),
            "category": md.get("category"),
            "tags": md.get("tags", []),
        },
        "measurement": {
            "model": summary.get("model"),
            "agent": summary.get("agent"),
            "n": metrics.get("n"),
            "c": metrics.get("c"),
            "p_hat": metrics.get("p_hat"),
            "ci95": metrics.get("ci95"),
            **{k: v for k, v in metrics.items() if k.startswith(("pass@", "pass^"))},
            "controls": summary.get("controls", {}),
            "validity": summary.get("validity", {}),
        },
        # The frozen contract. Changing any of these silently re-tiers the task,
        # so they travel with the data rather than living in a run log.
        "environment": {
            "seed": md.get("seed"),
            "knobs": md.get("knobs", {}),
            "apps": (env.get("env") or {}).get("MCP_STUMP_APPS"),
            "distractors": (env.get("env") or {}).get("MCP_STUMP_DISTRACTORS"),
            "presentation": (env.get("env") or {}).get("MCP_STUMP_PRESENTATION"),
            "network_mode": env.get("network_mode"),
        },
        "ground_truth": {
            "positive_key_paths": len(spec.get("positive", [])),
            "negative_key_paths": len(spec.get("negative", [])),
            "gold_plan_nodes": len(plan),
            "derived_from": "oracle execution",
            # Equal function sets are not yet resolved for this sandbox; when
            # they are, an unresolved set is a false-negative reward source.
            "equal_function_sets": None,
        },
        "usage": summary.get("usage", {}),
        "failure_breakdown": summary.get("failure_breakdown", {}),
        "canary": {
            "task_files": "eval-only, canary-stamped, never train on these",
            "trajectories": "training product, no canary",
        },
    }


def package(trials: Path, task_dir: Path, dest: Path, model: str | None = None) -> Path:
    """Turn a completed trials directory into a delivery bundle."""
    summary = _load(trials / "summary.json", {})
    model = model or summary.get("model", "model")
    slug = "".join(c if c.isalnum() or c in "-._" else "-" for c in str(model))

    dest.mkdir(parents=True, exist_ok=True)

    # 1. the reusable task package (minus staged scoring code, which is
    #    regenerated by scripts/materialize-task.sh and would double the size)
    task_out = dest / "task"
    if task_out.exists():
        shutil.rmtree(task_out)
    shutil.copytree(
        task_dir, task_out,
        ignore=shutil.ignore_patterns("mcp_stump", "__pycache__", "*.pyc"),
    )

    # 2. jobs: controls, then attempts under the model that produced them
    jobs = dest / "jobs"
    for control in ("oracle", "nop"):
        src = trials / "controls" / control
        if src.is_dir():
            shutil.copytree(src, jobs / control, dirs_exist_ok=True)

    attempts = sorted(p for p in trials.glob("run*") if p.is_dir())
    for i, run in enumerate(attempts, start=1):
        shutil.copytree(run, jobs / slug / f"attempt-{i}", dirs_exist_ok=True)

    # 3. training artifacts
    for name in ("pairs.jsonl", "failure_analysis.json"):
        src = trials / name
        if src.is_file():
            shutil.copy2(src, dest / name)

    # 4. manifest
    manifest = build_manifest(summary, task_dir, trials)
    manifest["bundle"] = {
        "attempts": len(attempts),
        "pairs": sum(1 for _ in (dest / "pairs.jsonl").open())
                 if (dest / "pairs.jsonl").is_file() else 0,
    }
    (dest / "manifest.json").write_text(json.dumps(manifest, indent=2))
    return dest
