#!/usr/bin/env python3
"""Regenerate software/utils/seed_content_registry.py.

A4 reconciliation: `task.toml`'s per-task `seed` and `software.utils.world_data`'s
per-task `world_data`/`fixture` are two independent content mechanisms. Seed
*always* drives `self.rng` (ids/timestamps/minted values, see
tests/test_seed_plumbing.py) but for most apps the substantive content
(listings, tickets, messages, ...) is loaded from a static per-app corpus and
does NOT change across seeds -- that's intentional, not a bug (see the
docstring on that test file). Declaring a per-task `seed` for one of those
apps without also supplying `world_data`/`fixture` silently implies content
varies when it doesn't.

This script empirically classifies every app by constructing its session
class at seed=42 and seed=999 (COMPLEXMCP_WORLD_DATA/COMPLEXMCP_FIXTURE
unset, so nothing masks the seed's own effect) and diffing get_session_dict()
output. It writes the result into seed_content_registry.CONTENT_VARIES_BY_SEED
so run_benchmark.py can warn at task-load time instead of task authors
discovering it by staring at a diff.

Re-run this whenever an app's generation logic changes:
    .venv/bin/python3 scripts/classify_seed_content.py --apply
(without --apply it just prints the diff against the committed registry)
"""
import argparse
import glob
import importlib
import json
import logging
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY_PATH = os.path.join(ROOT, "software", "utils", "seed_content_registry.py")

HEADER = '''"""Empirically-derived registry: does an app's get_session_dict() content
actually change when the seed changes?

Generated by scripts/classify_seed_content.py -- DO NOT hand-edit. Re-run
that script (with --apply) after changing any app's world-generation logic.

Seed always drives self.rng (ids/timestamps/minted values -- see
tests/test_seed_plumbing.py); this registry is about substantive *content*
only. Apps mapped to False load a static per-app corpus, so declaring a
per-task seed for them has no visible effect on content -- per-task content
variation for those apps must come from world_data hydration
(software.utils.world_data) or a fixture overlay (software.utils.fixtures),
not from seed. See run_benchmark.py's seed/world_data wiring and
seed/BUNDLE_SCHEMA.md's task.toml metadata contract for how this is used.
"""

CONTENT_VARIES_BY_SEED = {
'''


def classify():
    sys.path.insert(0, ROOT)
    os.chdir(ROOT)
    os.environ.pop("COMPLEXMCP_WORLD_DATA", None)
    os.environ.pop("COMPLEXMCP_FIXTURE", None)
    logging.disable(logging.CRITICAL)

    results = {}
    for app_dir in sorted(glob.glob("software/Light*")):
        app = os.path.basename(app_dir)
        if app in ("LightNews", "LightSystem"):
            continue  # no state -- see complexmcp-lightsystem-implicit-app memory
        session_cls = None
        for path in sorted(glob.glob(f"{app_dir}/*.py")):
            modname = path[:-3].replace("/", ".")
            try:
                module = importlib.import_module(modname)
            except Exception:
                continue
            for name in dir(module):
                obj = getattr(module, name)
                if isinstance(obj, type) and hasattr(obj, "get_session_dict"):
                    session_cls = obj
                    break
            if session_cls:
                break
        if session_cls is None:
            print(f"WARN: {app}: no session class found, skipping", file=sys.stderr)
            continue
        try:
            d42 = session_cls(os_cfg=None, seed=42).get_session_dict()
            d999 = session_cls(os_cfg=None, seed=999).get_session_dict()
        except Exception as e:
            print(f"WARN: {app}: {type(e).__name__}: {e}", file=sys.stderr)
            continue
        varies = json.dumps(d42, default=str, sort_keys=True) != json.dumps(d999, default=str, sort_keys=True)
        results[app] = varies
    return results


def render(results):
    lines = [HEADER]
    for app in sorted(results):
        lines.append(f"    {app!r}: {results[app]!r},\n")
    lines.append("}\n\n\n")
    lines.append('''def seed_rolls_content(app_name: str) -> bool:
    """True if `app_name`'s get_session_dict() content actually changes with
    seed. Unknown apps default to True (assume seed-varying) so a newly
    added app that hasn't been classified yet never triggers a false
    reconciliation warning -- silence, not noise, is the safe default."""
    return CONTENT_VARIES_BY_SEED.get(app_name, True)
''')
    return "".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true", help="write the registry file")
    args = parser.parse_args()

    results = classify()
    rendered = render(results)

    varies = sum(1 for v in results.values() if v)
    static = sum(1 for v in results.values() if not v)
    print(f"classified {len(results)} apps: {varies} vary by seed, {static} static", file=sys.stderr)

    if args.apply:
        with open(REGISTRY_PATH, "w") as fh:
            fh.write(rendered)
        print(f"wrote {REGISTRY_PATH}", file=sys.stderr)
    else:
        old = ""
        if os.path.exists(REGISTRY_PATH):
            old = open(REGISTRY_PATH).read()
        if old == rendered:
            print("registry up to date", file=sys.stderr)
        else:
            print("registry OUT OF DATE -- rerun with --apply", file=sys.stderr)
            sys.exit(1)


if __name__ == "__main__":
    main()
